# Jekyll Configuration

# Site Settings
url: "https://mekkop.github.io/Primal/"
website_url: "https://mekkop.github.io/Primal/"
title: Primal
email: MekkLovesMales@gmail.com
images-path: /static/images/
videos-path: /static/videos/
js-path: /static/js/
baseurl: "" # the subpath of your site, e.g. /blog

# Post Settings
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
highlighter: rouge

# Sass settings
sass:
    style: :compressed

# Collections
collections:
    collection_nav_links:
      output: false
    collection_projects:
      output: false
    collection_social:
      output: false

# Content
content:

  ## Personal information
  bio_tagline: "primalcheats.pro"
  bio_job_desc: "An enhancement for Ark: Survival Evolved"
  bio_contact: "https://discord.gg/U9DCQ9Mg3Q"
